import "./globals.css";
import localFont from "next/font/local";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const gabarito = localFont({
	src: "/font/Gabarito-VariableFont_wght.ttf",
});

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={gabarito.className}>{children}</body>
		</html>
	);
}
